// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dominant$Dominant from "./Dominant.bs.js";

require('isomorphic-fetch')
;

function dominantColors(param, param$1) {
  return Dominant$Dominant.ofUrl("YOUR_URL", param, param$1);
}

export {
  dominantColors ,
  
}
/*  Not a pure module */
